/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayDuatRaceRouteImport } from './routes/play.duat-race'
import { Route as AppVideoDemoRouteImport } from './routes/_app/video-demo'
import { Route as AppTimerRouteImport } from './routes/_app/timer'
import { Route as AppSevaRouteImport } from './routes/_app/seva'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMaterialRouteImport } from './routes/_app/material'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppImagesRouteImport } from './routes/_app/images'
import { Route as AppHomeworkRouteImport } from './routes/_app/homework'
import { Route as AppForumRouteImport } from './routes/_app/forum'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDirectoryRouteImport } from './routes/_app/directory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCoreRouteImport } from './routes/_app/core'
import { Route as AppBhaktiRouteImport } from './routes/_app/bhakti'
import { Route as AppPathwaysIndexRouteImport } from './routes/_app/pathways.index'
import { Route as AppHomeworkIndexRouteImport } from './routes/_app/homework.index'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups.index'
import { Route as AppForumIndexRouteImport } from './routes/_app/forum.index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses.index'
import { Route as AppCoreIndexRouteImport } from './routes/_app/core.index'
import { Route as AppTeachStudentsRouteImport } from './routes/_app/teach.students'
import { Route as AppTeachHomeworkRouteImport } from './routes/_app/teach.homework'
import { Route as AppTeachEventsRouteImport } from './routes/_app/teach.events'
import { Route as AppHomeworkAssignmentIdRouteImport } from './routes/_app/homework.$assignmentId'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups.$groupId'
import { Route as AppForumActivityRouteImport } from './routes/_app/forum.activity'
import { Route as AppForumCategorySlugRouteImport } from './routes/_app/forum.$categorySlug'
import { Route as AppCoreTratakaRouteImport } from './routes/_app/core.trataka'
import { Route as AppCoreSelfEnquiryRouteImport } from './routes/_app/core.self-enquiry'
import { Route as AppTeachHomeworkIndexRouteImport } from './routes/_app/teach.homework.index'
import { Route as AppPathwaysYogicIndexRouteImport } from './routes/_app/pathways.yogic.index'
import { Route as AppPathwaysTantricIndexRouteImport } from './routes/_app/pathways.tantric.index'
import { Route as AppPathwaysMagickIndexRouteImport } from './routes/_app/pathways.magick.index'
import { Route as AppPathwaysDaoistIndexRouteImport } from './routes/_app/pathways.daoist.index'
import { Route as AppPathwaysBuddhistIndexRouteImport } from './routes/_app/pathways.buddhist.index'
import { Route as AppForumCategorySlugIndexRouteImport } from './routes/_app/forum.$categorySlug.index'
import { Route as AppTeachSubmissionsSubmissionIdRouteImport } from './routes/_app/teach.submissions.$submissionId'
import { Route as AppTeachHomeworkNewRouteImport } from './routes/_app/teach.homework.new'
import { Route as AppTeachHomeworkAssignmentIdRouteImport } from './routes/_app/teach.homework.$assignmentId'
import { Route as AppPathwaysYogicSuryaNamaskaraRouteImport } from './routes/_app/pathways.yogic.surya-namaskara'
import { Route as AppPathwaysYogicNadiShodhanaRouteImport } from './routes/_app/pathways.yogic.nadi-shodhana'
import { Route as AppPathwaysYogicHubRouteImport } from './routes/_app/pathways.yogic.hub'
import { Route as AppPathwaysYogicChakrasRouteImport } from './routes/_app/pathways.yogic.chakras'
import { Route as AppPathwaysYogicCourseSlugRouteImport } from './routes/_app/pathways.yogic.$courseSlug'
import { Route as AppPathwaysTantricYantraRouteImport } from './routes/_app/pathways.tantric.yantra'
import { Route as AppPathwaysTantricTattwaShuddhiRouteImport } from './routes/_app/pathways.tantric.tattwa-shuddhi'
import { Route as AppPathwaysTantricNyasaRouteImport } from './routes/_app/pathways.tantric.nyasa'
import { Route as AppPathwaysTantricMantraRouteImport } from './routes/_app/pathways.tantric.mantra'
import { Route as AppPathwaysTantricMahavidyasRouteImport } from './routes/_app/pathways.tantric.mahavidyas'
import { Route as AppPathwaysTantricHubRouteImport } from './routes/_app/pathways.tantric.hub'
import { Route as AppPathwaysTantricCosmologyRouteImport } from './routes/_app/pathways.tantric.cosmology'
import { Route as AppPathwaysTantricCourseSlugRouteImport } from './routes/_app/pathways.tantric.$courseSlug'
import { Route as AppPathwaysMagickTreeOfLifeRouteImport } from './routes/_app/pathways.magick.tree-of-life'
import { Route as AppPathwaysMagickSpagyricsRouteImport } from './routes/_app/pathways.magick.spagyrics'
import { Route as AppPathwaysMagickHubRouteImport } from './routes/_app/pathways.magick.hub'
import { Route as AppPathwaysMagickHoursRouteImport } from './routes/_app/pathways.magick.hours'
import { Route as AppPathwaysMagickCourseSlugRouteImport } from './routes/_app/pathways.magick.$courseSlug'
import { Route as AppPathwaysDaoistIchingRouteImport } from './routes/_app/pathways.daoist.iching'
import { Route as AppPathwaysDaoistHubRouteImport } from './routes/_app/pathways.daoist.hub'
import { Route as AppPathwaysDaoistCosmologyRouteImport } from './routes/_app/pathways.daoist.cosmology'
import { Route as AppPathwaysDaoistBaguaTaijiRouteImport } from './routes/_app/pathways.daoist.bagua-taiji'
import { Route as AppPathwaysDaoistCourseSlugRouteImport } from './routes/_app/pathways.daoist.$courseSlug'
import { Route as AppPathwaysBuddhistHubRouteImport } from './routes/_app/pathways.buddhist.hub'
import { Route as AppPathwaysBuddhistDeitiesRouteImport } from './routes/_app/pathways.buddhist.deities'
import { Route as AppPathwaysBuddhistCourseSlugRouteImport } from './routes/_app/pathways.buddhist.$courseSlug'
import { Route as AppForumCategorySlugThreadIdRouteImport } from './routes/_app/forum.$categorySlug.$threadId'
import { Route as AppCoursesPathwaySlugRouteImport } from './routes/_app/courses.$pathway.$slug'
import { Route as AppPathwaysYogicChakrasIndexRouteImport } from './routes/_app/pathways.yogic.chakras.index'
import { Route as AppPathwaysTantricMahavidyasIndexRouteImport } from './routes/_app/pathways.tantric.mahavidyas.index'
import { Route as AppPathwaysDaoistBaguaTaijiIndexRouteImport } from './routes/_app/pathways.daoist.bagua-taiji.index'
import { Route as AppPathwaysDaoistCourseSlugIndexRouteImport } from './routes/_app/pathways.daoist.$courseSlug.index'
import { Route as AppPathwaysBuddhistDeitiesIndexRouteImport } from './routes/_app/pathways.buddhist.deities.index'
import { Route as AppPathwaysYogicChakrasChakraSlugRouteImport } from './routes/_app/pathways.yogic.chakras.$chakraSlug'
import { Route as AppPathwaysTantricMahavidyasGoddessSlugRouteImport } from './routes/_app/pathways.tantric.mahavidyas.$goddessSlug'
import { Route as AppPathwaysDaoistBaguaTaijiAboutRouteImport } from './routes/_app/pathways.daoist.bagua-taiji.about'
import { Route as AppPathwaysDaoistBaguaTaijiTopicSlugRouteImport } from './routes/_app/pathways.daoist.bagua-taiji.$topicSlug'
import { Route as AppPathwaysDaoistCourseSlugLessonSlugRouteImport } from './routes/_app/pathways.daoist.$courseSlug.$lessonSlug'
import { Route as AppPathwaysBuddhistDeitiesDeitySlugRouteImport } from './routes/_app/pathways.buddhist.deities.$deitySlug'
import { Route as AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRouteImport } from './routes/_app/pathways.daoist.$courseSlug.meridians.$meridianSlug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDuatRaceRoute = PlayDuatRaceRouteImport.update({
  id: '/play/duat-race',
  path: '/play/duat-race',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideoDemoRoute = AppVideoDemoRouteImport.update({
  id: '/video-demo',
  path: '/video-demo',
  getParentRoute: () => AppRoute,
} as any)
const AppTimerRoute = AppTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AppRoute,
} as any)
const AppSevaRoute = AppSevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialRoute = AppMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkRoute = AppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppForumRoute = AppForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreRoute = AppCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => AppRoute,
} as any)
const AppBhaktiRoute = AppBhaktiRouteImport.update({
  id: '/bhakti',
  path: '/bhakti',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysIndexRoute = AppPathwaysIndexRouteImport.update({
  id: '/pathways/',
  path: '/pathways/',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkIndexRoute = AppHomeworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeworkRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppForumIndexRoute = AppForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppForumRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppCoreIndexRoute = AppCoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoreRoute,
} as any)
const AppTeachStudentsRoute = AppTeachStudentsRouteImport.update({
  id: '/teach/students',
  path: '/teach/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachHomeworkRoute = AppTeachHomeworkRouteImport.update({
  id: '/teach/homework',
  path: '/teach/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachEventsRoute = AppTeachEventsRouteImport.update({
  id: '/teach/events',
  path: '/teach/events',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkAssignmentIdRoute = AppHomeworkAssignmentIdRouteImport.update({
  id: '/$assignmentId',
  path: '/$assignmentId',
  getParentRoute: () => AppHomeworkRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppForumActivityRoute = AppForumActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppForumRoute,
} as any)
const AppForumCategorySlugRoute = AppForumCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => AppForumRoute,
} as any)
const AppCoreTratakaRoute = AppCoreTratakaRouteImport.update({
  id: '/trataka',
  path: '/trataka',
  getParentRoute: () => AppCoreRoute,
} as any)
const AppCoreSelfEnquiryRoute = AppCoreSelfEnquiryRouteImport.update({
  id: '/self-enquiry',
  path: '/self-enquiry',
  getParentRoute: () => AppCoreRoute,
} as any)
const AppTeachHomeworkIndexRoute = AppTeachHomeworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeachHomeworkRoute,
} as any)
const AppPathwaysYogicIndexRoute = AppPathwaysYogicIndexRouteImport.update({
  id: '/pathways/yogic/',
  path: '/pathways/yogic/',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysTantricIndexRoute = AppPathwaysTantricIndexRouteImport.update({
  id: '/pathways/tantric/',
  path: '/pathways/tantric/',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysMagickIndexRoute = AppPathwaysMagickIndexRouteImport.update({
  id: '/pathways/magick/',
  path: '/pathways/magick/',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysDaoistIndexRoute = AppPathwaysDaoistIndexRouteImport.update({
  id: '/pathways/daoist/',
  path: '/pathways/daoist/',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysBuddhistIndexRoute =
  AppPathwaysBuddhistIndexRouteImport.update({
    id: '/pathways/buddhist/',
    path: '/pathways/buddhist/',
    getParentRoute: () => AppRoute,
  } as any)
const AppForumCategorySlugIndexRoute =
  AppForumCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppForumCategorySlugRoute,
  } as any)
const AppTeachSubmissionsSubmissionIdRoute =
  AppTeachSubmissionsSubmissionIdRouteImport.update({
    id: '/teach/submissions/$submissionId',
    path: '/teach/submissions/$submissionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeachHomeworkNewRoute = AppTeachHomeworkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTeachHomeworkRoute,
} as any)
const AppTeachHomeworkAssignmentIdRoute =
  AppTeachHomeworkAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => AppTeachHomeworkRoute,
  } as any)
const AppPathwaysYogicSuryaNamaskaraRoute =
  AppPathwaysYogicSuryaNamaskaraRouteImport.update({
    id: '/pathways/yogic/surya-namaskara',
    path: '/pathways/yogic/surya-namaskara',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysYogicNadiShodhanaRoute =
  AppPathwaysYogicNadiShodhanaRouteImport.update({
    id: '/pathways/yogic/nadi-shodhana',
    path: '/pathways/yogic/nadi-shodhana',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysYogicHubRoute = AppPathwaysYogicHubRouteImport.update({
  id: '/pathways/yogic/hub',
  path: '/pathways/yogic/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysYogicChakrasRoute = AppPathwaysYogicChakrasRouteImport.update({
  id: '/pathways/yogic/chakras',
  path: '/pathways/yogic/chakras',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysYogicCourseSlugRoute =
  AppPathwaysYogicCourseSlugRouteImport.update({
    id: '/pathways/yogic/$courseSlug',
    path: '/pathways/yogic/$courseSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricYantraRoute =
  AppPathwaysTantricYantraRouteImport.update({
    id: '/pathways/tantric/yantra',
    path: '/pathways/tantric/yantra',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricTattwaShuddhiRoute =
  AppPathwaysTantricTattwaShuddhiRouteImport.update({
    id: '/pathways/tantric/tattwa-shuddhi',
    path: '/pathways/tantric/tattwa-shuddhi',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricNyasaRoute = AppPathwaysTantricNyasaRouteImport.update({
  id: '/pathways/tantric/nyasa',
  path: '/pathways/tantric/nyasa',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysTantricMantraRoute =
  AppPathwaysTantricMantraRouteImport.update({
    id: '/pathways/tantric/mantra',
    path: '/pathways/tantric/mantra',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricMahavidyasRoute =
  AppPathwaysTantricMahavidyasRouteImport.update({
    id: '/pathways/tantric/mahavidyas',
    path: '/pathways/tantric/mahavidyas',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricHubRoute = AppPathwaysTantricHubRouteImport.update({
  id: '/pathways/tantric/hub',
  path: '/pathways/tantric/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysTantricCosmologyRoute =
  AppPathwaysTantricCosmologyRouteImport.update({
    id: '/pathways/tantric/cosmology',
    path: '/pathways/tantric/cosmology',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysTantricCourseSlugRoute =
  AppPathwaysTantricCourseSlugRouteImport.update({
    id: '/pathways/tantric/$courseSlug',
    path: '/pathways/tantric/$courseSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysMagickTreeOfLifeRoute =
  AppPathwaysMagickTreeOfLifeRouteImport.update({
    id: '/pathways/magick/tree-of-life',
    path: '/pathways/magick/tree-of-life',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysMagickSpagyricsRoute =
  AppPathwaysMagickSpagyricsRouteImport.update({
    id: '/pathways/magick/spagyrics',
    path: '/pathways/magick/spagyrics',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysMagickHubRoute = AppPathwaysMagickHubRouteImport.update({
  id: '/pathways/magick/hub',
  path: '/pathways/magick/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysMagickHoursRoute = AppPathwaysMagickHoursRouteImport.update({
  id: '/pathways/magick/hours',
  path: '/pathways/magick/hours',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysMagickCourseSlugRoute =
  AppPathwaysMagickCourseSlugRouteImport.update({
    id: '/pathways/magick/$courseSlug',
    path: '/pathways/magick/$courseSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysDaoistIchingRoute = AppPathwaysDaoistIchingRouteImport.update({
  id: '/pathways/daoist/iching',
  path: '/pathways/daoist/iching',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysDaoistHubRoute = AppPathwaysDaoistHubRouteImport.update({
  id: '/pathways/daoist/hub',
  path: '/pathways/daoist/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysDaoistCosmologyRoute =
  AppPathwaysDaoistCosmologyRouteImport.update({
    id: '/pathways/daoist/cosmology',
    path: '/pathways/daoist/cosmology',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysDaoistBaguaTaijiRoute =
  AppPathwaysDaoistBaguaTaijiRouteImport.update({
    id: '/pathways/daoist/bagua-taiji',
    path: '/pathways/daoist/bagua-taiji',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysDaoistCourseSlugRoute =
  AppPathwaysDaoistCourseSlugRouteImport.update({
    id: '/pathways/daoist/$courseSlug',
    path: '/pathways/daoist/$courseSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysBuddhistHubRoute = AppPathwaysBuddhistHubRouteImport.update({
  id: '/pathways/buddhist/hub',
  path: '/pathways/buddhist/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwaysBuddhistDeitiesRoute =
  AppPathwaysBuddhistDeitiesRouteImport.update({
    id: '/pathways/buddhist/deities',
    path: '/pathways/buddhist/deities',
    getParentRoute: () => AppRoute,
  } as any)
const AppPathwaysBuddhistCourseSlugRoute =
  AppPathwaysBuddhistCourseSlugRouteImport.update({
    id: '/pathways/buddhist/$courseSlug',
    path: '/pathways/buddhist/$courseSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppForumCategorySlugThreadIdRoute =
  AppForumCategorySlugThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AppForumCategorySlugRoute,
  } as any)
const AppCoursesPathwaySlugRoute = AppCoursesPathwaySlugRouteImport.update({
  id: '/$pathway/$slug',
  path: '/$pathway/$slug',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppPathwaysYogicChakrasIndexRoute =
  AppPathwaysYogicChakrasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPathwaysYogicChakrasRoute,
  } as any)
const AppPathwaysTantricMahavidyasIndexRoute =
  AppPathwaysTantricMahavidyasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPathwaysTantricMahavidyasRoute,
  } as any)
const AppPathwaysDaoistBaguaTaijiIndexRoute =
  AppPathwaysDaoistBaguaTaijiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPathwaysDaoistBaguaTaijiRoute,
  } as any)
const AppPathwaysDaoistCourseSlugIndexRoute =
  AppPathwaysDaoistCourseSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPathwaysDaoistCourseSlugRoute,
  } as any)
const AppPathwaysBuddhistDeitiesIndexRoute =
  AppPathwaysBuddhistDeitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPathwaysBuddhistDeitiesRoute,
  } as any)
const AppPathwaysYogicChakrasChakraSlugRoute =
  AppPathwaysYogicChakrasChakraSlugRouteImport.update({
    id: '/$chakraSlug',
    path: '/$chakraSlug',
    getParentRoute: () => AppPathwaysYogicChakrasRoute,
  } as any)
const AppPathwaysTantricMahavidyasGoddessSlugRoute =
  AppPathwaysTantricMahavidyasGoddessSlugRouteImport.update({
    id: '/$goddessSlug',
    path: '/$goddessSlug',
    getParentRoute: () => AppPathwaysTantricMahavidyasRoute,
  } as any)
const AppPathwaysDaoistBaguaTaijiAboutRoute =
  AppPathwaysDaoistBaguaTaijiAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AppPathwaysDaoistBaguaTaijiRoute,
  } as any)
const AppPathwaysDaoistBaguaTaijiTopicSlugRoute =
  AppPathwaysDaoistBaguaTaijiTopicSlugRouteImport.update({
    id: '/$topicSlug',
    path: '/$topicSlug',
    getParentRoute: () => AppPathwaysDaoistBaguaTaijiRoute,
  } as any)
const AppPathwaysDaoistCourseSlugLessonSlugRoute =
  AppPathwaysDaoistCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AppPathwaysDaoistCourseSlugRoute,
  } as any)
const AppPathwaysBuddhistDeitiesDeitySlugRoute =
  AppPathwaysBuddhistDeitiesDeitySlugRouteImport.update({
    id: '/$deitySlug',
    path: '/$deitySlug',
    getParentRoute: () => AppPathwaysBuddhistDeitiesRoute,
  } as any)
const AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute =
  AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRouteImport.update({
    id: '/meridians/$meridianSlug',
    path: '/meridians/$meridianSlug',
    getParentRoute: () => AppPathwaysDaoistCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bhakti': typeof AppBhaktiRoute
  '/core': typeof AppCoreRouteWithChildren
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/directory': typeof AppDirectoryRoute
  '/events': typeof AppEventsRoute
  '/forum': typeof AppForumRouteWithChildren
  '/homework': typeof AppHomeworkRouteWithChildren
  '/images': typeof AppImagesRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/material': typeof AppMaterialRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/schedule': typeof AppScheduleRoute
  '/seva': typeof AppSevaRoute
  '/timer': typeof AppTimerRoute
  '/video-demo': typeof AppVideoDemoRoute
  '/play/duat-race': typeof PlayDuatRaceRoute
  '/core/self-enquiry': typeof AppCoreSelfEnquiryRoute
  '/core/trataka': typeof AppCoreTratakaRoute
  '/forum/$categorySlug': typeof AppForumCategorySlugRouteWithChildren
  '/forum/activity': typeof AppForumActivityRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/teach/events': typeof AppTeachEventsRoute
  '/teach/homework': typeof AppTeachHomeworkRouteWithChildren
  '/teach/students': typeof AppTeachStudentsRoute
  '/core/': typeof AppCoreIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/forum/': typeof AppForumIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/homework/': typeof AppHomeworkIndexRoute
  '/pathways/': typeof AppPathwaysIndexRoute
  '/courses/$pathway/$slug': typeof AppCoursesPathwaySlugRoute
  '/forum/$categorySlug/$threadId': typeof AppForumCategorySlugThreadIdRoute
  '/pathways/buddhist/$courseSlug': typeof AppPathwaysBuddhistCourseSlugRoute
  '/pathways/buddhist/deities': typeof AppPathwaysBuddhistDeitiesRouteWithChildren
  '/pathways/buddhist/hub': typeof AppPathwaysBuddhistHubRoute
  '/pathways/daoist/$courseSlug': typeof AppPathwaysDaoistCourseSlugRouteWithChildren
  '/pathways/daoist/bagua-taiji': typeof AppPathwaysDaoistBaguaTaijiRouteWithChildren
  '/pathways/daoist/cosmology': typeof AppPathwaysDaoistCosmologyRoute
  '/pathways/daoist/hub': typeof AppPathwaysDaoistHubRoute
  '/pathways/daoist/iching': typeof AppPathwaysDaoistIchingRoute
  '/pathways/magick/$courseSlug': typeof AppPathwaysMagickCourseSlugRoute
  '/pathways/magick/hours': typeof AppPathwaysMagickHoursRoute
  '/pathways/magick/hub': typeof AppPathwaysMagickHubRoute
  '/pathways/magick/spagyrics': typeof AppPathwaysMagickSpagyricsRoute
  '/pathways/magick/tree-of-life': typeof AppPathwaysMagickTreeOfLifeRoute
  '/pathways/tantric/$courseSlug': typeof AppPathwaysTantricCourseSlugRoute
  '/pathways/tantric/cosmology': typeof AppPathwaysTantricCosmologyRoute
  '/pathways/tantric/hub': typeof AppPathwaysTantricHubRoute
  '/pathways/tantric/mahavidyas': typeof AppPathwaysTantricMahavidyasRouteWithChildren
  '/pathways/tantric/mantra': typeof AppPathwaysTantricMantraRoute
  '/pathways/tantric/nyasa': typeof AppPathwaysTantricNyasaRoute
  '/pathways/tantric/tattwa-shuddhi': typeof AppPathwaysTantricTattwaShuddhiRoute
  '/pathways/tantric/yantra': typeof AppPathwaysTantricYantraRoute
  '/pathways/yogic/$courseSlug': typeof AppPathwaysYogicCourseSlugRoute
  '/pathways/yogic/chakras': typeof AppPathwaysYogicChakrasRouteWithChildren
  '/pathways/yogic/hub': typeof AppPathwaysYogicHubRoute
  '/pathways/yogic/nadi-shodhana': typeof AppPathwaysYogicNadiShodhanaRoute
  '/pathways/yogic/surya-namaskara': typeof AppPathwaysYogicSuryaNamaskaraRoute
  '/teach/homework/$assignmentId': typeof AppTeachHomeworkAssignmentIdRoute
  '/teach/homework/new': typeof AppTeachHomeworkNewRoute
  '/teach/submissions/$submissionId': typeof AppTeachSubmissionsSubmissionIdRoute
  '/forum/$categorySlug/': typeof AppForumCategorySlugIndexRoute
  '/pathways/buddhist/': typeof AppPathwaysBuddhistIndexRoute
  '/pathways/daoist/': typeof AppPathwaysDaoistIndexRoute
  '/pathways/magick/': typeof AppPathwaysMagickIndexRoute
  '/pathways/tantric/': typeof AppPathwaysTantricIndexRoute
  '/pathways/yogic/': typeof AppPathwaysYogicIndexRoute
  '/teach/homework/': typeof AppTeachHomeworkIndexRoute
  '/pathways/buddhist/deities/$deitySlug': typeof AppPathwaysBuddhistDeitiesDeitySlugRoute
  '/pathways/daoist/$courseSlug/$lessonSlug': typeof AppPathwaysDaoistCourseSlugLessonSlugRoute
  '/pathways/daoist/bagua-taiji/$topicSlug': typeof AppPathwaysDaoistBaguaTaijiTopicSlugRoute
  '/pathways/daoist/bagua-taiji/about': typeof AppPathwaysDaoistBaguaTaijiAboutRoute
  '/pathways/tantric/mahavidyas/$goddessSlug': typeof AppPathwaysTantricMahavidyasGoddessSlugRoute
  '/pathways/yogic/chakras/$chakraSlug': typeof AppPathwaysYogicChakrasChakraSlugRoute
  '/pathways/buddhist/deities/': typeof AppPathwaysBuddhistDeitiesIndexRoute
  '/pathways/daoist/$courseSlug/': typeof AppPathwaysDaoistCourseSlugIndexRoute
  '/pathways/daoist/bagua-taiji/': typeof AppPathwaysDaoistBaguaTaijiIndexRoute
  '/pathways/tantric/mahavidyas/': typeof AppPathwaysTantricMahavidyasIndexRoute
  '/pathways/yogic/chakras/': typeof AppPathwaysYogicChakrasIndexRoute
  '/pathways/daoist/$courseSlug/meridians/$meridianSlug': typeof AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bhakti': typeof AppBhaktiRoute
  '/dashboard': typeof AppDashboardRoute
  '/directory': typeof AppDirectoryRoute
  '/events': typeof AppEventsRoute
  '/images': typeof AppImagesRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/material': typeof AppMaterialRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/schedule': typeof AppScheduleRoute
  '/seva': typeof AppSevaRoute
  '/timer': typeof AppTimerRoute
  '/video-demo': typeof AppVideoDemoRoute
  '/play/duat-race': typeof PlayDuatRaceRoute
  '/core/self-enquiry': typeof AppCoreSelfEnquiryRoute
  '/core/trataka': typeof AppCoreTratakaRoute
  '/forum/activity': typeof AppForumActivityRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/teach/events': typeof AppTeachEventsRoute
  '/teach/students': typeof AppTeachStudentsRoute
  '/core': typeof AppCoreIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/forum': typeof AppForumIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/homework': typeof AppHomeworkIndexRoute
  '/pathways': typeof AppPathwaysIndexRoute
  '/courses/$pathway/$slug': typeof AppCoursesPathwaySlugRoute
  '/forum/$categorySlug/$threadId': typeof AppForumCategorySlugThreadIdRoute
  '/pathways/buddhist/$courseSlug': typeof AppPathwaysBuddhistCourseSlugRoute
  '/pathways/buddhist/hub': typeof AppPathwaysBuddhistHubRoute
  '/pathways/daoist/cosmology': typeof AppPathwaysDaoistCosmologyRoute
  '/pathways/daoist/hub': typeof AppPathwaysDaoistHubRoute
  '/pathways/daoist/iching': typeof AppPathwaysDaoistIchingRoute
  '/pathways/magick/$courseSlug': typeof AppPathwaysMagickCourseSlugRoute
  '/pathways/magick/hours': typeof AppPathwaysMagickHoursRoute
  '/pathways/magick/hub': typeof AppPathwaysMagickHubRoute
  '/pathways/magick/spagyrics': typeof AppPathwaysMagickSpagyricsRoute
  '/pathways/magick/tree-of-life': typeof AppPathwaysMagickTreeOfLifeRoute
  '/pathways/tantric/$courseSlug': typeof AppPathwaysTantricCourseSlugRoute
  '/pathways/tantric/cosmology': typeof AppPathwaysTantricCosmologyRoute
  '/pathways/tantric/hub': typeof AppPathwaysTantricHubRoute
  '/pathways/tantric/mantra': typeof AppPathwaysTantricMantraRoute
  '/pathways/tantric/nyasa': typeof AppPathwaysTantricNyasaRoute
  '/pathways/tantric/tattwa-shuddhi': typeof AppPathwaysTantricTattwaShuddhiRoute
  '/pathways/tantric/yantra': typeof AppPathwaysTantricYantraRoute
  '/pathways/yogic/$courseSlug': typeof AppPathwaysYogicCourseSlugRoute
  '/pathways/yogic/hub': typeof AppPathwaysYogicHubRoute
  '/pathways/yogic/nadi-shodhana': typeof AppPathwaysYogicNadiShodhanaRoute
  '/pathways/yogic/surya-namaskara': typeof AppPathwaysYogicSuryaNamaskaraRoute
  '/teach/homework/$assignmentId': typeof AppTeachHomeworkAssignmentIdRoute
  '/teach/homework/new': typeof AppTeachHomeworkNewRoute
  '/teach/submissions/$submissionId': typeof AppTeachSubmissionsSubmissionIdRoute
  '/forum/$categorySlug': typeof AppForumCategorySlugIndexRoute
  '/pathways/buddhist': typeof AppPathwaysBuddhistIndexRoute
  '/pathways/daoist': typeof AppPathwaysDaoistIndexRoute
  '/pathways/magick': typeof AppPathwaysMagickIndexRoute
  '/pathways/tantric': typeof AppPathwaysTantricIndexRoute
  '/pathways/yogic': typeof AppPathwaysYogicIndexRoute
  '/teach/homework': typeof AppTeachHomeworkIndexRoute
  '/pathways/buddhist/deities/$deitySlug': typeof AppPathwaysBuddhistDeitiesDeitySlugRoute
  '/pathways/daoist/$courseSlug/$lessonSlug': typeof AppPathwaysDaoistCourseSlugLessonSlugRoute
  '/pathways/daoist/bagua-taiji/$topicSlug': typeof AppPathwaysDaoistBaguaTaijiTopicSlugRoute
  '/pathways/daoist/bagua-taiji/about': typeof AppPathwaysDaoistBaguaTaijiAboutRoute
  '/pathways/tantric/mahavidyas/$goddessSlug': typeof AppPathwaysTantricMahavidyasGoddessSlugRoute
  '/pathways/yogic/chakras/$chakraSlug': typeof AppPathwaysYogicChakrasChakraSlugRoute
  '/pathways/buddhist/deities': typeof AppPathwaysBuddhistDeitiesIndexRoute
  '/pathways/daoist/$courseSlug': typeof AppPathwaysDaoistCourseSlugIndexRoute
  '/pathways/daoist/bagua-taiji': typeof AppPathwaysDaoistBaguaTaijiIndexRoute
  '/pathways/tantric/mahavidyas': typeof AppPathwaysTantricMahavidyasIndexRoute
  '/pathways/yogic/chakras': typeof AppPathwaysYogicChakrasIndexRoute
  '/pathways/daoist/$courseSlug/meridians/$meridianSlug': typeof AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bhakti': typeof AppBhaktiRoute
  '/_app/core': typeof AppCoreRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/directory': typeof AppDirectoryRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/forum': typeof AppForumRouteWithChildren
  '/_app/homework': typeof AppHomeworkRouteWithChildren
  '/_app/images': typeof AppImagesRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/material': typeof AppMaterialRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/seva': typeof AppSevaRoute
  '/_app/timer': typeof AppTimerRoute
  '/_app/video-demo': typeof AppVideoDemoRoute
  '/play/duat-race': typeof PlayDuatRaceRoute
  '/_app/core/self-enquiry': typeof AppCoreSelfEnquiryRoute
  '/_app/core/trataka': typeof AppCoreTratakaRoute
  '/_app/forum/$categorySlug': typeof AppForumCategorySlugRouteWithChildren
  '/_app/forum/activity': typeof AppForumActivityRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/_app/teach/events': typeof AppTeachEventsRoute
  '/_app/teach/homework': typeof AppTeachHomeworkRouteWithChildren
  '/_app/teach/students': typeof AppTeachStudentsRoute
  '/_app/core/': typeof AppCoreIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/forum/': typeof AppForumIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/homework/': typeof AppHomeworkIndexRoute
  '/_app/pathways/': typeof AppPathwaysIndexRoute
  '/_app/courses/$pathway/$slug': typeof AppCoursesPathwaySlugRoute
  '/_app/forum/$categorySlug/$threadId': typeof AppForumCategorySlugThreadIdRoute
  '/_app/pathways/buddhist/$courseSlug': typeof AppPathwaysBuddhistCourseSlugRoute
  '/_app/pathways/buddhist/deities': typeof AppPathwaysBuddhistDeitiesRouteWithChildren
  '/_app/pathways/buddhist/hub': typeof AppPathwaysBuddhistHubRoute
  '/_app/pathways/daoist/$courseSlug': typeof AppPathwaysDaoistCourseSlugRouteWithChildren
  '/_app/pathways/daoist/bagua-taiji': typeof AppPathwaysDaoistBaguaTaijiRouteWithChildren
  '/_app/pathways/daoist/cosmology': typeof AppPathwaysDaoistCosmologyRoute
  '/_app/pathways/daoist/hub': typeof AppPathwaysDaoistHubRoute
  '/_app/pathways/daoist/iching': typeof AppPathwaysDaoistIchingRoute
  '/_app/pathways/magick/$courseSlug': typeof AppPathwaysMagickCourseSlugRoute
  '/_app/pathways/magick/hours': typeof AppPathwaysMagickHoursRoute
  '/_app/pathways/magick/hub': typeof AppPathwaysMagickHubRoute
  '/_app/pathways/magick/spagyrics': typeof AppPathwaysMagickSpagyricsRoute
  '/_app/pathways/magick/tree-of-life': typeof AppPathwaysMagickTreeOfLifeRoute
  '/_app/pathways/tantric/$courseSlug': typeof AppPathwaysTantricCourseSlugRoute
  '/_app/pathways/tantric/cosmology': typeof AppPathwaysTantricCosmologyRoute
  '/_app/pathways/tantric/hub': typeof AppPathwaysTantricHubRoute
  '/_app/pathways/tantric/mahavidyas': typeof AppPathwaysTantricMahavidyasRouteWithChildren
  '/_app/pathways/tantric/mantra': typeof AppPathwaysTantricMantraRoute
  '/_app/pathways/tantric/nyasa': typeof AppPathwaysTantricNyasaRoute
  '/_app/pathways/tantric/tattwa-shuddhi': typeof AppPathwaysTantricTattwaShuddhiRoute
  '/_app/pathways/tantric/yantra': typeof AppPathwaysTantricYantraRoute
  '/_app/pathways/yogic/$courseSlug': typeof AppPathwaysYogicCourseSlugRoute
  '/_app/pathways/yogic/chakras': typeof AppPathwaysYogicChakrasRouteWithChildren
  '/_app/pathways/yogic/hub': typeof AppPathwaysYogicHubRoute
  '/_app/pathways/yogic/nadi-shodhana': typeof AppPathwaysYogicNadiShodhanaRoute
  '/_app/pathways/yogic/surya-namaskara': typeof AppPathwaysYogicSuryaNamaskaraRoute
  '/_app/teach/homework/$assignmentId': typeof AppTeachHomeworkAssignmentIdRoute
  '/_app/teach/homework/new': typeof AppTeachHomeworkNewRoute
  '/_app/teach/submissions/$submissionId': typeof AppTeachSubmissionsSubmissionIdRoute
  '/_app/forum/$categorySlug/': typeof AppForumCategorySlugIndexRoute
  '/_app/pathways/buddhist/': typeof AppPathwaysBuddhistIndexRoute
  '/_app/pathways/daoist/': typeof AppPathwaysDaoistIndexRoute
  '/_app/pathways/magick/': typeof AppPathwaysMagickIndexRoute
  '/_app/pathways/tantric/': typeof AppPathwaysTantricIndexRoute
  '/_app/pathways/yogic/': typeof AppPathwaysYogicIndexRoute
  '/_app/teach/homework/': typeof AppTeachHomeworkIndexRoute
  '/_app/pathways/buddhist/deities/$deitySlug': typeof AppPathwaysBuddhistDeitiesDeitySlugRoute
  '/_app/pathways/daoist/$courseSlug/$lessonSlug': typeof AppPathwaysDaoistCourseSlugLessonSlugRoute
  '/_app/pathways/daoist/bagua-taiji/$topicSlug': typeof AppPathwaysDaoistBaguaTaijiTopicSlugRoute
  '/_app/pathways/daoist/bagua-taiji/about': typeof AppPathwaysDaoistBaguaTaijiAboutRoute
  '/_app/pathways/tantric/mahavidyas/$goddessSlug': typeof AppPathwaysTantricMahavidyasGoddessSlugRoute
  '/_app/pathways/yogic/chakras/$chakraSlug': typeof AppPathwaysYogicChakrasChakraSlugRoute
  '/_app/pathways/buddhist/deities/': typeof AppPathwaysBuddhistDeitiesIndexRoute
  '/_app/pathways/daoist/$courseSlug/': typeof AppPathwaysDaoistCourseSlugIndexRoute
  '/_app/pathways/daoist/bagua-taiji/': typeof AppPathwaysDaoistBaguaTaijiIndexRoute
  '/_app/pathways/tantric/mahavidyas/': typeof AppPathwaysTantricMahavidyasIndexRoute
  '/_app/pathways/yogic/chakras/': typeof AppPathwaysYogicChakrasIndexRoute
  '/_app/pathways/daoist/$courseSlug/meridians/$meridianSlug': typeof AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bhakti'
    | '/core'
    | '/courses'
    | '/dashboard'
    | '/directory'
    | '/events'
    | '/forum'
    | '/homework'
    | '/images'
    | '/journal'
    | '/library'
    | '/material'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/schedule'
    | '/seva'
    | '/timer'
    | '/video-demo'
    | '/play/duat-race'
    | '/core/self-enquiry'
    | '/core/trataka'
    | '/forum/$categorySlug'
    | '/forum/activity'
    | '/groups/$groupId'
    | '/homework/$assignmentId'
    | '/teach/events'
    | '/teach/homework'
    | '/teach/students'
    | '/core/'
    | '/courses/'
    | '/forum/'
    | '/groups/'
    | '/homework/'
    | '/pathways/'
    | '/courses/$pathway/$slug'
    | '/forum/$categorySlug/$threadId'
    | '/pathways/buddhist/$courseSlug'
    | '/pathways/buddhist/deities'
    | '/pathways/buddhist/hub'
    | '/pathways/daoist/$courseSlug'
    | '/pathways/daoist/bagua-taiji'
    | '/pathways/daoist/cosmology'
    | '/pathways/daoist/hub'
    | '/pathways/daoist/iching'
    | '/pathways/magick/$courseSlug'
    | '/pathways/magick/hours'
    | '/pathways/magick/hub'
    | '/pathways/magick/spagyrics'
    | '/pathways/magick/tree-of-life'
    | '/pathways/tantric/$courseSlug'
    | '/pathways/tantric/cosmology'
    | '/pathways/tantric/hub'
    | '/pathways/tantric/mahavidyas'
    | '/pathways/tantric/mantra'
    | '/pathways/tantric/nyasa'
    | '/pathways/tantric/tattwa-shuddhi'
    | '/pathways/tantric/yantra'
    | '/pathways/yogic/$courseSlug'
    | '/pathways/yogic/chakras'
    | '/pathways/yogic/hub'
    | '/pathways/yogic/nadi-shodhana'
    | '/pathways/yogic/surya-namaskara'
    | '/teach/homework/$assignmentId'
    | '/teach/homework/new'
    | '/teach/submissions/$submissionId'
    | '/forum/$categorySlug/'
    | '/pathways/buddhist/'
    | '/pathways/daoist/'
    | '/pathways/magick/'
    | '/pathways/tantric/'
    | '/pathways/yogic/'
    | '/teach/homework/'
    | '/pathways/buddhist/deities/$deitySlug'
    | '/pathways/daoist/$courseSlug/$lessonSlug'
    | '/pathways/daoist/bagua-taiji/$topicSlug'
    | '/pathways/daoist/bagua-taiji/about'
    | '/pathways/tantric/mahavidyas/$goddessSlug'
    | '/pathways/yogic/chakras/$chakraSlug'
    | '/pathways/buddhist/deities/'
    | '/pathways/daoist/$courseSlug/'
    | '/pathways/daoist/bagua-taiji/'
    | '/pathways/tantric/mahavidyas/'
    | '/pathways/yogic/chakras/'
    | '/pathways/daoist/$courseSlug/meridians/$meridianSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bhakti'
    | '/dashboard'
    | '/directory'
    | '/events'
    | '/images'
    | '/journal'
    | '/library'
    | '/material'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/schedule'
    | '/seva'
    | '/timer'
    | '/video-demo'
    | '/play/duat-race'
    | '/core/self-enquiry'
    | '/core/trataka'
    | '/forum/activity'
    | '/groups/$groupId'
    | '/homework/$assignmentId'
    | '/teach/events'
    | '/teach/students'
    | '/core'
    | '/courses'
    | '/forum'
    | '/groups'
    | '/homework'
    | '/pathways'
    | '/courses/$pathway/$slug'
    | '/forum/$categorySlug/$threadId'
    | '/pathways/buddhist/$courseSlug'
    | '/pathways/buddhist/hub'
    | '/pathways/daoist/cosmology'
    | '/pathways/daoist/hub'
    | '/pathways/daoist/iching'
    | '/pathways/magick/$courseSlug'
    | '/pathways/magick/hours'
    | '/pathways/magick/hub'
    | '/pathways/magick/spagyrics'
    | '/pathways/magick/tree-of-life'
    | '/pathways/tantric/$courseSlug'
    | '/pathways/tantric/cosmology'
    | '/pathways/tantric/hub'
    | '/pathways/tantric/mantra'
    | '/pathways/tantric/nyasa'
    | '/pathways/tantric/tattwa-shuddhi'
    | '/pathways/tantric/yantra'
    | '/pathways/yogic/$courseSlug'
    | '/pathways/yogic/hub'
    | '/pathways/yogic/nadi-shodhana'
    | '/pathways/yogic/surya-namaskara'
    | '/teach/homework/$assignmentId'
    | '/teach/homework/new'
    | '/teach/submissions/$submissionId'
    | '/forum/$categorySlug'
    | '/pathways/buddhist'
    | '/pathways/daoist'
    | '/pathways/magick'
    | '/pathways/tantric'
    | '/pathways/yogic'
    | '/teach/homework'
    | '/pathways/buddhist/deities/$deitySlug'
    | '/pathways/daoist/$courseSlug/$lessonSlug'
    | '/pathways/daoist/bagua-taiji/$topicSlug'
    | '/pathways/daoist/bagua-taiji/about'
    | '/pathways/tantric/mahavidyas/$goddessSlug'
    | '/pathways/yogic/chakras/$chakraSlug'
    | '/pathways/buddhist/deities'
    | '/pathways/daoist/$courseSlug'
    | '/pathways/daoist/bagua-taiji'
    | '/pathways/tantric/mahavidyas'
    | '/pathways/yogic/chakras'
    | '/pathways/daoist/$courseSlug/meridians/$meridianSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bhakti'
    | '/_app/core'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/directory'
    | '/_app/events'
    | '/_app/forum'
    | '/_app/homework'
    | '/_app/images'
    | '/_app/journal'
    | '/_app/library'
    | '/_app/material'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/schedule'
    | '/_app/seva'
    | '/_app/timer'
    | '/_app/video-demo'
    | '/play/duat-race'
    | '/_app/core/self-enquiry'
    | '/_app/core/trataka'
    | '/_app/forum/$categorySlug'
    | '/_app/forum/activity'
    | '/_app/groups/$groupId'
    | '/_app/homework/$assignmentId'
    | '/_app/teach/events'
    | '/_app/teach/homework'
    | '/_app/teach/students'
    | '/_app/core/'
    | '/_app/courses/'
    | '/_app/forum/'
    | '/_app/groups/'
    | '/_app/homework/'
    | '/_app/pathways/'
    | '/_app/courses/$pathway/$slug'
    | '/_app/forum/$categorySlug/$threadId'
    | '/_app/pathways/buddhist/$courseSlug'
    | '/_app/pathways/buddhist/deities'
    | '/_app/pathways/buddhist/hub'
    | '/_app/pathways/daoist/$courseSlug'
    | '/_app/pathways/daoist/bagua-taiji'
    | '/_app/pathways/daoist/cosmology'
    | '/_app/pathways/daoist/hub'
    | '/_app/pathways/daoist/iching'
    | '/_app/pathways/magick/$courseSlug'
    | '/_app/pathways/magick/hours'
    | '/_app/pathways/magick/hub'
    | '/_app/pathways/magick/spagyrics'
    | '/_app/pathways/magick/tree-of-life'
    | '/_app/pathways/tantric/$courseSlug'
    | '/_app/pathways/tantric/cosmology'
    | '/_app/pathways/tantric/hub'
    | '/_app/pathways/tantric/mahavidyas'
    | '/_app/pathways/tantric/mantra'
    | '/_app/pathways/tantric/nyasa'
    | '/_app/pathways/tantric/tattwa-shuddhi'
    | '/_app/pathways/tantric/yantra'
    | '/_app/pathways/yogic/$courseSlug'
    | '/_app/pathways/yogic/chakras'
    | '/_app/pathways/yogic/hub'
    | '/_app/pathways/yogic/nadi-shodhana'
    | '/_app/pathways/yogic/surya-namaskara'
    | '/_app/teach/homework/$assignmentId'
    | '/_app/teach/homework/new'
    | '/_app/teach/submissions/$submissionId'
    | '/_app/forum/$categorySlug/'
    | '/_app/pathways/buddhist/'
    | '/_app/pathways/daoist/'
    | '/_app/pathways/magick/'
    | '/_app/pathways/tantric/'
    | '/_app/pathways/yogic/'
    | '/_app/teach/homework/'
    | '/_app/pathways/buddhist/deities/$deitySlug'
    | '/_app/pathways/daoist/$courseSlug/$lessonSlug'
    | '/_app/pathways/daoist/bagua-taiji/$topicSlug'
    | '/_app/pathways/daoist/bagua-taiji/about'
    | '/_app/pathways/tantric/mahavidyas/$goddessSlug'
    | '/_app/pathways/yogic/chakras/$chakraSlug'
    | '/_app/pathways/buddhist/deities/'
    | '/_app/pathways/daoist/$courseSlug/'
    | '/_app/pathways/daoist/bagua-taiji/'
    | '/_app/pathways/tantric/mahavidyas/'
    | '/_app/pathways/yogic/chakras/'
    | '/_app/pathways/daoist/$courseSlug/meridians/$meridianSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayDuatRaceRoute: typeof PlayDuatRaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/duat-race': {
      id: '/play/duat-race'
      path: '/play/duat-race'
      fullPath: '/play/duat-race'
      preLoaderRoute: typeof PlayDuatRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/video-demo': {
      id: '/_app/video-demo'
      path: '/video-demo'
      fullPath: '/video-demo'
      preLoaderRoute: typeof AppVideoDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timer': {
      id: '/_app/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AppTimerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seva': {
      id: '/_app/seva'
      path: '/seva'
      fullPath: '/seva'
      preLoaderRoute: typeof AppSevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/material': {
      id: '/_app/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof AppMaterialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images': {
      id: '/_app/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework': {
      id: '/_app/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AppHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum': {
      id: '/_app/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AppForumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory': {
      id: '/_app/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core': {
      id: '/_app/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof AppCoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bhakti': {
      id: '/_app/bhakti'
      path: '/bhakti'
      fullPath: '/bhakti'
      preLoaderRoute: typeof AppBhaktiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/': {
      id: '/_app/pathways/'
      path: '/pathways'
      fullPath: '/pathways/'
      preLoaderRoute: typeof AppPathwaysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework/': {
      id: '/_app/homework/'
      path: '/'
      fullPath: '/homework/'
      preLoaderRoute: typeof AppHomeworkIndexRouteImport
      parentRoute: typeof AppHomeworkRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/': {
      id: '/_app/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof AppForumIndexRouteImport
      parentRoute: typeof AppForumRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/core/': {
      id: '/_app/core/'
      path: '/'
      fullPath: '/core/'
      preLoaderRoute: typeof AppCoreIndexRouteImport
      parentRoute: typeof AppCoreRoute
    }
    '/_app/teach/students': {
      id: '/_app/teach/students'
      path: '/teach/students'
      fullPath: '/teach/students'
      preLoaderRoute: typeof AppTeachStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teach/homework': {
      id: '/_app/teach/homework'
      path: '/teach/homework'
      fullPath: '/teach/homework'
      preLoaderRoute: typeof AppTeachHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teach/events': {
      id: '/_app/teach/events'
      path: '/teach/events'
      fullPath: '/teach/events'
      preLoaderRoute: typeof AppTeachEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework/$assignmentId': {
      id: '/_app/homework/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/homework/$assignmentId'
      preLoaderRoute: typeof AppHomeworkAssignmentIdRouteImport
      parentRoute: typeof AppHomeworkRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/activity': {
      id: '/_app/forum/activity'
      path: '/activity'
      fullPath: '/forum/activity'
      preLoaderRoute: typeof AppForumActivityRouteImport
      parentRoute: typeof AppForumRoute
    }
    '/_app/forum/$categorySlug': {
      id: '/_app/forum/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/forum/$categorySlug'
      preLoaderRoute: typeof AppForumCategorySlugRouteImport
      parentRoute: typeof AppForumRoute
    }
    '/_app/core/trataka': {
      id: '/_app/core/trataka'
      path: '/trataka'
      fullPath: '/core/trataka'
      preLoaderRoute: typeof AppCoreTratakaRouteImport
      parentRoute: typeof AppCoreRoute
    }
    '/_app/core/self-enquiry': {
      id: '/_app/core/self-enquiry'
      path: '/self-enquiry'
      fullPath: '/core/self-enquiry'
      preLoaderRoute: typeof AppCoreSelfEnquiryRouteImport
      parentRoute: typeof AppCoreRoute
    }
    '/_app/teach/homework/': {
      id: '/_app/teach/homework/'
      path: '/'
      fullPath: '/teach/homework/'
      preLoaderRoute: typeof AppTeachHomeworkIndexRouteImport
      parentRoute: typeof AppTeachHomeworkRoute
    }
    '/_app/pathways/yogic/': {
      id: '/_app/pathways/yogic/'
      path: '/pathways/yogic'
      fullPath: '/pathways/yogic/'
      preLoaderRoute: typeof AppPathwaysYogicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/': {
      id: '/_app/pathways/tantric/'
      path: '/pathways/tantric'
      fullPath: '/pathways/tantric/'
      preLoaderRoute: typeof AppPathwaysTantricIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/': {
      id: '/_app/pathways/magick/'
      path: '/pathways/magick'
      fullPath: '/pathways/magick/'
      preLoaderRoute: typeof AppPathwaysMagickIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/': {
      id: '/_app/pathways/daoist/'
      path: '/pathways/daoist'
      fullPath: '/pathways/daoist/'
      preLoaderRoute: typeof AppPathwaysDaoistIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/buddhist/': {
      id: '/_app/pathways/buddhist/'
      path: '/pathways/buddhist'
      fullPath: '/pathways/buddhist/'
      preLoaderRoute: typeof AppPathwaysBuddhistIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/$categorySlug/': {
      id: '/_app/forum/$categorySlug/'
      path: '/'
      fullPath: '/forum/$categorySlug/'
      preLoaderRoute: typeof AppForumCategorySlugIndexRouteImport
      parentRoute: typeof AppForumCategorySlugRoute
    }
    '/_app/teach/submissions/$submissionId': {
      id: '/_app/teach/submissions/$submissionId'
      path: '/teach/submissions/$submissionId'
      fullPath: '/teach/submissions/$submissionId'
      preLoaderRoute: typeof AppTeachSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teach/homework/new': {
      id: '/_app/teach/homework/new'
      path: '/new'
      fullPath: '/teach/homework/new'
      preLoaderRoute: typeof AppTeachHomeworkNewRouteImport
      parentRoute: typeof AppTeachHomeworkRoute
    }
    '/_app/teach/homework/$assignmentId': {
      id: '/_app/teach/homework/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/teach/homework/$assignmentId'
      preLoaderRoute: typeof AppTeachHomeworkAssignmentIdRouteImport
      parentRoute: typeof AppTeachHomeworkRoute
    }
    '/_app/pathways/yogic/surya-namaskara': {
      id: '/_app/pathways/yogic/surya-namaskara'
      path: '/pathways/yogic/surya-namaskara'
      fullPath: '/pathways/yogic/surya-namaskara'
      preLoaderRoute: typeof AppPathwaysYogicSuryaNamaskaraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/yogic/nadi-shodhana': {
      id: '/_app/pathways/yogic/nadi-shodhana'
      path: '/pathways/yogic/nadi-shodhana'
      fullPath: '/pathways/yogic/nadi-shodhana'
      preLoaderRoute: typeof AppPathwaysYogicNadiShodhanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/yogic/hub': {
      id: '/_app/pathways/yogic/hub'
      path: '/pathways/yogic/hub'
      fullPath: '/pathways/yogic/hub'
      preLoaderRoute: typeof AppPathwaysYogicHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/yogic/chakras': {
      id: '/_app/pathways/yogic/chakras'
      path: '/pathways/yogic/chakras'
      fullPath: '/pathways/yogic/chakras'
      preLoaderRoute: typeof AppPathwaysYogicChakrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/yogic/$courseSlug': {
      id: '/_app/pathways/yogic/$courseSlug'
      path: '/pathways/yogic/$courseSlug'
      fullPath: '/pathways/yogic/$courseSlug'
      preLoaderRoute: typeof AppPathwaysYogicCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/yantra': {
      id: '/_app/pathways/tantric/yantra'
      path: '/pathways/tantric/yantra'
      fullPath: '/pathways/tantric/yantra'
      preLoaderRoute: typeof AppPathwaysTantricYantraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/tattwa-shuddhi': {
      id: '/_app/pathways/tantric/tattwa-shuddhi'
      path: '/pathways/tantric/tattwa-shuddhi'
      fullPath: '/pathways/tantric/tattwa-shuddhi'
      preLoaderRoute: typeof AppPathwaysTantricTattwaShuddhiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/nyasa': {
      id: '/_app/pathways/tantric/nyasa'
      path: '/pathways/tantric/nyasa'
      fullPath: '/pathways/tantric/nyasa'
      preLoaderRoute: typeof AppPathwaysTantricNyasaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/mantra': {
      id: '/_app/pathways/tantric/mantra'
      path: '/pathways/tantric/mantra'
      fullPath: '/pathways/tantric/mantra'
      preLoaderRoute: typeof AppPathwaysTantricMantraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/mahavidyas': {
      id: '/_app/pathways/tantric/mahavidyas'
      path: '/pathways/tantric/mahavidyas'
      fullPath: '/pathways/tantric/mahavidyas'
      preLoaderRoute: typeof AppPathwaysTantricMahavidyasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/hub': {
      id: '/_app/pathways/tantric/hub'
      path: '/pathways/tantric/hub'
      fullPath: '/pathways/tantric/hub'
      preLoaderRoute: typeof AppPathwaysTantricHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/cosmology': {
      id: '/_app/pathways/tantric/cosmology'
      path: '/pathways/tantric/cosmology'
      fullPath: '/pathways/tantric/cosmology'
      preLoaderRoute: typeof AppPathwaysTantricCosmologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/tantric/$courseSlug': {
      id: '/_app/pathways/tantric/$courseSlug'
      path: '/pathways/tantric/$courseSlug'
      fullPath: '/pathways/tantric/$courseSlug'
      preLoaderRoute: typeof AppPathwaysTantricCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/tree-of-life': {
      id: '/_app/pathways/magick/tree-of-life'
      path: '/pathways/magick/tree-of-life'
      fullPath: '/pathways/magick/tree-of-life'
      preLoaderRoute: typeof AppPathwaysMagickTreeOfLifeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/spagyrics': {
      id: '/_app/pathways/magick/spagyrics'
      path: '/pathways/magick/spagyrics'
      fullPath: '/pathways/magick/spagyrics'
      preLoaderRoute: typeof AppPathwaysMagickSpagyricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/hub': {
      id: '/_app/pathways/magick/hub'
      path: '/pathways/magick/hub'
      fullPath: '/pathways/magick/hub'
      preLoaderRoute: typeof AppPathwaysMagickHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/hours': {
      id: '/_app/pathways/magick/hours'
      path: '/pathways/magick/hours'
      fullPath: '/pathways/magick/hours'
      preLoaderRoute: typeof AppPathwaysMagickHoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/magick/$courseSlug': {
      id: '/_app/pathways/magick/$courseSlug'
      path: '/pathways/magick/$courseSlug'
      fullPath: '/pathways/magick/$courseSlug'
      preLoaderRoute: typeof AppPathwaysMagickCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/iching': {
      id: '/_app/pathways/daoist/iching'
      path: '/pathways/daoist/iching'
      fullPath: '/pathways/daoist/iching'
      preLoaderRoute: typeof AppPathwaysDaoistIchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/hub': {
      id: '/_app/pathways/daoist/hub'
      path: '/pathways/daoist/hub'
      fullPath: '/pathways/daoist/hub'
      preLoaderRoute: typeof AppPathwaysDaoistHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/cosmology': {
      id: '/_app/pathways/daoist/cosmology'
      path: '/pathways/daoist/cosmology'
      fullPath: '/pathways/daoist/cosmology'
      preLoaderRoute: typeof AppPathwaysDaoistCosmologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/bagua-taiji': {
      id: '/_app/pathways/daoist/bagua-taiji'
      path: '/pathways/daoist/bagua-taiji'
      fullPath: '/pathways/daoist/bagua-taiji'
      preLoaderRoute: typeof AppPathwaysDaoistBaguaTaijiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/daoist/$courseSlug': {
      id: '/_app/pathways/daoist/$courseSlug'
      path: '/pathways/daoist/$courseSlug'
      fullPath: '/pathways/daoist/$courseSlug'
      preLoaderRoute: typeof AppPathwaysDaoistCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/buddhist/hub': {
      id: '/_app/pathways/buddhist/hub'
      path: '/pathways/buddhist/hub'
      fullPath: '/pathways/buddhist/hub'
      preLoaderRoute: typeof AppPathwaysBuddhistHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/buddhist/deities': {
      id: '/_app/pathways/buddhist/deities'
      path: '/pathways/buddhist/deities'
      fullPath: '/pathways/buddhist/deities'
      preLoaderRoute: typeof AppPathwaysBuddhistDeitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pathways/buddhist/$courseSlug': {
      id: '/_app/pathways/buddhist/$courseSlug'
      path: '/pathways/buddhist/$courseSlug'
      fullPath: '/pathways/buddhist/$courseSlug'
      preLoaderRoute: typeof AppPathwaysBuddhistCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/$categorySlug/$threadId': {
      id: '/_app/forum/$categorySlug/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$categorySlug/$threadId'
      preLoaderRoute: typeof AppForumCategorySlugThreadIdRouteImport
      parentRoute: typeof AppForumCategorySlugRoute
    }
    '/_app/courses/$pathway/$slug': {
      id: '/_app/courses/$pathway/$slug'
      path: '/$pathway/$slug'
      fullPath: '/courses/$pathway/$slug'
      preLoaderRoute: typeof AppCoursesPathwaySlugRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/pathways/yogic/chakras/': {
      id: '/_app/pathways/yogic/chakras/'
      path: '/'
      fullPath: '/pathways/yogic/chakras/'
      preLoaderRoute: typeof AppPathwaysYogicChakrasIndexRouteImport
      parentRoute: typeof AppPathwaysYogicChakrasRoute
    }
    '/_app/pathways/tantric/mahavidyas/': {
      id: '/_app/pathways/tantric/mahavidyas/'
      path: '/'
      fullPath: '/pathways/tantric/mahavidyas/'
      preLoaderRoute: typeof AppPathwaysTantricMahavidyasIndexRouteImport
      parentRoute: typeof AppPathwaysTantricMahavidyasRoute
    }
    '/_app/pathways/daoist/bagua-taiji/': {
      id: '/_app/pathways/daoist/bagua-taiji/'
      path: '/'
      fullPath: '/pathways/daoist/bagua-taiji/'
      preLoaderRoute: typeof AppPathwaysDaoistBaguaTaijiIndexRouteImport
      parentRoute: typeof AppPathwaysDaoistBaguaTaijiRoute
    }
    '/_app/pathways/daoist/$courseSlug/': {
      id: '/_app/pathways/daoist/$courseSlug/'
      path: '/'
      fullPath: '/pathways/daoist/$courseSlug/'
      preLoaderRoute: typeof AppPathwaysDaoistCourseSlugIndexRouteImport
      parentRoute: typeof AppPathwaysDaoistCourseSlugRoute
    }
    '/_app/pathways/buddhist/deities/': {
      id: '/_app/pathways/buddhist/deities/'
      path: '/'
      fullPath: '/pathways/buddhist/deities/'
      preLoaderRoute: typeof AppPathwaysBuddhistDeitiesIndexRouteImport
      parentRoute: typeof AppPathwaysBuddhistDeitiesRoute
    }
    '/_app/pathways/yogic/chakras/$chakraSlug': {
      id: '/_app/pathways/yogic/chakras/$chakraSlug'
      path: '/$chakraSlug'
      fullPath: '/pathways/yogic/chakras/$chakraSlug'
      preLoaderRoute: typeof AppPathwaysYogicChakrasChakraSlugRouteImport
      parentRoute: typeof AppPathwaysYogicChakrasRoute
    }
    '/_app/pathways/tantric/mahavidyas/$goddessSlug': {
      id: '/_app/pathways/tantric/mahavidyas/$goddessSlug'
      path: '/$goddessSlug'
      fullPath: '/pathways/tantric/mahavidyas/$goddessSlug'
      preLoaderRoute: typeof AppPathwaysTantricMahavidyasGoddessSlugRouteImport
      parentRoute: typeof AppPathwaysTantricMahavidyasRoute
    }
    '/_app/pathways/daoist/bagua-taiji/about': {
      id: '/_app/pathways/daoist/bagua-taiji/about'
      path: '/about'
      fullPath: '/pathways/daoist/bagua-taiji/about'
      preLoaderRoute: typeof AppPathwaysDaoistBaguaTaijiAboutRouteImport
      parentRoute: typeof AppPathwaysDaoistBaguaTaijiRoute
    }
    '/_app/pathways/daoist/bagua-taiji/$topicSlug': {
      id: '/_app/pathways/daoist/bagua-taiji/$topicSlug'
      path: '/$topicSlug'
      fullPath: '/pathways/daoist/bagua-taiji/$topicSlug'
      preLoaderRoute: typeof AppPathwaysDaoistBaguaTaijiTopicSlugRouteImport
      parentRoute: typeof AppPathwaysDaoistBaguaTaijiRoute
    }
    '/_app/pathways/daoist/$courseSlug/$lessonSlug': {
      id: '/_app/pathways/daoist/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/pathways/daoist/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AppPathwaysDaoistCourseSlugLessonSlugRouteImport
      parentRoute: typeof AppPathwaysDaoistCourseSlugRoute
    }
    '/_app/pathways/buddhist/deities/$deitySlug': {
      id: '/_app/pathways/buddhist/deities/$deitySlug'
      path: '/$deitySlug'
      fullPath: '/pathways/buddhist/deities/$deitySlug'
      preLoaderRoute: typeof AppPathwaysBuddhistDeitiesDeitySlugRouteImport
      parentRoute: typeof AppPathwaysBuddhistDeitiesRoute
    }
    '/_app/pathways/daoist/$courseSlug/meridians/$meridianSlug': {
      id: '/_app/pathways/daoist/$courseSlug/meridians/$meridianSlug'
      path: '/meridians/$meridianSlug'
      fullPath: '/pathways/daoist/$courseSlug/meridians/$meridianSlug'
      preLoaderRoute: typeof AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRouteImport
      parentRoute: typeof AppPathwaysDaoistCourseSlugRoute
    }
  }
}

interface AppCoreRouteChildren {
  AppCoreSelfEnquiryRoute: typeof AppCoreSelfEnquiryRoute
  AppCoreTratakaRoute: typeof AppCoreTratakaRoute
  AppCoreIndexRoute: typeof AppCoreIndexRoute
}

const AppCoreRouteChildren: AppCoreRouteChildren = {
  AppCoreSelfEnquiryRoute: AppCoreSelfEnquiryRoute,
  AppCoreTratakaRoute: AppCoreTratakaRoute,
  AppCoreIndexRoute: AppCoreIndexRoute,
}

const AppCoreRouteWithChildren =
  AppCoreRoute._addFileChildren(AppCoreRouteChildren)

interface AppCoursesRouteChildren {
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesPathwaySlugRoute: typeof AppCoursesPathwaySlugRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesPathwaySlugRoute: AppCoursesPathwaySlugRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppForumCategorySlugRouteChildren {
  AppForumCategorySlugThreadIdRoute: typeof AppForumCategorySlugThreadIdRoute
  AppForumCategorySlugIndexRoute: typeof AppForumCategorySlugIndexRoute
}

const AppForumCategorySlugRouteChildren: AppForumCategorySlugRouteChildren = {
  AppForumCategorySlugThreadIdRoute: AppForumCategorySlugThreadIdRoute,
  AppForumCategorySlugIndexRoute: AppForumCategorySlugIndexRoute,
}

const AppForumCategorySlugRouteWithChildren =
  AppForumCategorySlugRoute._addFileChildren(AppForumCategorySlugRouteChildren)

interface AppForumRouteChildren {
  AppForumCategorySlugRoute: typeof AppForumCategorySlugRouteWithChildren
  AppForumActivityRoute: typeof AppForumActivityRoute
  AppForumIndexRoute: typeof AppForumIndexRoute
}

const AppForumRouteChildren: AppForumRouteChildren = {
  AppForumCategorySlugRoute: AppForumCategorySlugRouteWithChildren,
  AppForumActivityRoute: AppForumActivityRoute,
  AppForumIndexRoute: AppForumIndexRoute,
}

const AppForumRouteWithChildren = AppForumRoute._addFileChildren(
  AppForumRouteChildren,
)

interface AppHomeworkRouteChildren {
  AppHomeworkAssignmentIdRoute: typeof AppHomeworkAssignmentIdRoute
  AppHomeworkIndexRoute: typeof AppHomeworkIndexRoute
}

const AppHomeworkRouteChildren: AppHomeworkRouteChildren = {
  AppHomeworkAssignmentIdRoute: AppHomeworkAssignmentIdRoute,
  AppHomeworkIndexRoute: AppHomeworkIndexRoute,
}

const AppHomeworkRouteWithChildren = AppHomeworkRoute._addFileChildren(
  AppHomeworkRouteChildren,
)

interface AppTeachHomeworkRouteChildren {
  AppTeachHomeworkAssignmentIdRoute: typeof AppTeachHomeworkAssignmentIdRoute
  AppTeachHomeworkNewRoute: typeof AppTeachHomeworkNewRoute
  AppTeachHomeworkIndexRoute: typeof AppTeachHomeworkIndexRoute
}

const AppTeachHomeworkRouteChildren: AppTeachHomeworkRouteChildren = {
  AppTeachHomeworkAssignmentIdRoute: AppTeachHomeworkAssignmentIdRoute,
  AppTeachHomeworkNewRoute: AppTeachHomeworkNewRoute,
  AppTeachHomeworkIndexRoute: AppTeachHomeworkIndexRoute,
}

const AppTeachHomeworkRouteWithChildren =
  AppTeachHomeworkRoute._addFileChildren(AppTeachHomeworkRouteChildren)

interface AppPathwaysBuddhistDeitiesRouteChildren {
  AppPathwaysBuddhistDeitiesDeitySlugRoute: typeof AppPathwaysBuddhistDeitiesDeitySlugRoute
  AppPathwaysBuddhistDeitiesIndexRoute: typeof AppPathwaysBuddhistDeitiesIndexRoute
}

const AppPathwaysBuddhistDeitiesRouteChildren: AppPathwaysBuddhistDeitiesRouteChildren =
  {
    AppPathwaysBuddhistDeitiesDeitySlugRoute:
      AppPathwaysBuddhistDeitiesDeitySlugRoute,
    AppPathwaysBuddhistDeitiesIndexRoute: AppPathwaysBuddhistDeitiesIndexRoute,
  }

const AppPathwaysBuddhistDeitiesRouteWithChildren =
  AppPathwaysBuddhistDeitiesRoute._addFileChildren(
    AppPathwaysBuddhistDeitiesRouteChildren,
  )

interface AppPathwaysDaoistCourseSlugRouteChildren {
  AppPathwaysDaoistCourseSlugLessonSlugRoute: typeof AppPathwaysDaoistCourseSlugLessonSlugRoute
  AppPathwaysDaoistCourseSlugIndexRoute: typeof AppPathwaysDaoistCourseSlugIndexRoute
  AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute: typeof AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute
}

const AppPathwaysDaoistCourseSlugRouteChildren: AppPathwaysDaoistCourseSlugRouteChildren =
  {
    AppPathwaysDaoistCourseSlugLessonSlugRoute:
      AppPathwaysDaoistCourseSlugLessonSlugRoute,
    AppPathwaysDaoistCourseSlugIndexRoute:
      AppPathwaysDaoistCourseSlugIndexRoute,
    AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute:
      AppPathwaysDaoistCourseSlugMeridiansMeridianSlugRoute,
  }

const AppPathwaysDaoistCourseSlugRouteWithChildren =
  AppPathwaysDaoistCourseSlugRoute._addFileChildren(
    AppPathwaysDaoistCourseSlugRouteChildren,
  )

interface AppPathwaysDaoistBaguaTaijiRouteChildren {
  AppPathwaysDaoistBaguaTaijiTopicSlugRoute: typeof AppPathwaysDaoistBaguaTaijiTopicSlugRoute
  AppPathwaysDaoistBaguaTaijiAboutRoute: typeof AppPathwaysDaoistBaguaTaijiAboutRoute
  AppPathwaysDaoistBaguaTaijiIndexRoute: typeof AppPathwaysDaoistBaguaTaijiIndexRoute
}

const AppPathwaysDaoistBaguaTaijiRouteChildren: AppPathwaysDaoistBaguaTaijiRouteChildren =
  {
    AppPathwaysDaoistBaguaTaijiTopicSlugRoute:
      AppPathwaysDaoistBaguaTaijiTopicSlugRoute,
    AppPathwaysDaoistBaguaTaijiAboutRoute:
      AppPathwaysDaoistBaguaTaijiAboutRoute,
    AppPathwaysDaoistBaguaTaijiIndexRoute:
      AppPathwaysDaoistBaguaTaijiIndexRoute,
  }

const AppPathwaysDaoistBaguaTaijiRouteWithChildren =
  AppPathwaysDaoistBaguaTaijiRoute._addFileChildren(
    AppPathwaysDaoistBaguaTaijiRouteChildren,
  )

interface AppPathwaysTantricMahavidyasRouteChildren {
  AppPathwaysTantricMahavidyasGoddessSlugRoute: typeof AppPathwaysTantricMahavidyasGoddessSlugRoute
  AppPathwaysTantricMahavidyasIndexRoute: typeof AppPathwaysTantricMahavidyasIndexRoute
}

const AppPathwaysTantricMahavidyasRouteChildren: AppPathwaysTantricMahavidyasRouteChildren =
  {
    AppPathwaysTantricMahavidyasGoddessSlugRoute:
      AppPathwaysTantricMahavidyasGoddessSlugRoute,
    AppPathwaysTantricMahavidyasIndexRoute:
      AppPathwaysTantricMahavidyasIndexRoute,
  }

const AppPathwaysTantricMahavidyasRouteWithChildren =
  AppPathwaysTantricMahavidyasRoute._addFileChildren(
    AppPathwaysTantricMahavidyasRouteChildren,
  )

interface AppPathwaysYogicChakrasRouteChildren {
  AppPathwaysYogicChakrasChakraSlugRoute: typeof AppPathwaysYogicChakrasChakraSlugRoute
  AppPathwaysYogicChakrasIndexRoute: typeof AppPathwaysYogicChakrasIndexRoute
}

const AppPathwaysYogicChakrasRouteChildren: AppPathwaysYogicChakrasRouteChildren =
  {
    AppPathwaysYogicChakrasChakraSlugRoute:
      AppPathwaysYogicChakrasChakraSlugRoute,
    AppPathwaysYogicChakrasIndexRoute: AppPathwaysYogicChakrasIndexRoute,
  }

const AppPathwaysYogicChakrasRouteWithChildren =
  AppPathwaysYogicChakrasRoute._addFileChildren(
    AppPathwaysYogicChakrasRouteChildren,
  )

interface AppRouteChildren {
  AppBhaktiRoute: typeof AppBhaktiRoute
  AppCoreRoute: typeof AppCoreRouteWithChildren
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppEventsRoute: typeof AppEventsRoute
  AppForumRoute: typeof AppForumRouteWithChildren
  AppHomeworkRoute: typeof AppHomeworkRouteWithChildren
  AppImagesRoute: typeof AppImagesRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMaterialRoute: typeof AppMaterialRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSevaRoute: typeof AppSevaRoute
  AppTimerRoute: typeof AppTimerRoute
  AppVideoDemoRoute: typeof AppVideoDemoRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppTeachEventsRoute: typeof AppTeachEventsRoute
  AppTeachHomeworkRoute: typeof AppTeachHomeworkRouteWithChildren
  AppTeachStudentsRoute: typeof AppTeachStudentsRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppPathwaysIndexRoute: typeof AppPathwaysIndexRoute
  AppPathwaysBuddhistCourseSlugRoute: typeof AppPathwaysBuddhistCourseSlugRoute
  AppPathwaysBuddhistDeitiesRoute: typeof AppPathwaysBuddhistDeitiesRouteWithChildren
  AppPathwaysBuddhistHubRoute: typeof AppPathwaysBuddhistHubRoute
  AppPathwaysDaoistCourseSlugRoute: typeof AppPathwaysDaoistCourseSlugRouteWithChildren
  AppPathwaysDaoistBaguaTaijiRoute: typeof AppPathwaysDaoistBaguaTaijiRouteWithChildren
  AppPathwaysDaoistCosmologyRoute: typeof AppPathwaysDaoistCosmologyRoute
  AppPathwaysDaoistHubRoute: typeof AppPathwaysDaoistHubRoute
  AppPathwaysDaoistIchingRoute: typeof AppPathwaysDaoistIchingRoute
  AppPathwaysMagickCourseSlugRoute: typeof AppPathwaysMagickCourseSlugRoute
  AppPathwaysMagickHoursRoute: typeof AppPathwaysMagickHoursRoute
  AppPathwaysMagickHubRoute: typeof AppPathwaysMagickHubRoute
  AppPathwaysMagickSpagyricsRoute: typeof AppPathwaysMagickSpagyricsRoute
  AppPathwaysMagickTreeOfLifeRoute: typeof AppPathwaysMagickTreeOfLifeRoute
  AppPathwaysTantricCourseSlugRoute: typeof AppPathwaysTantricCourseSlugRoute
  AppPathwaysTantricCosmologyRoute: typeof AppPathwaysTantricCosmologyRoute
  AppPathwaysTantricHubRoute: typeof AppPathwaysTantricHubRoute
  AppPathwaysTantricMahavidyasRoute: typeof AppPathwaysTantricMahavidyasRouteWithChildren
  AppPathwaysTantricMantraRoute: typeof AppPathwaysTantricMantraRoute
  AppPathwaysTantricNyasaRoute: typeof AppPathwaysTantricNyasaRoute
  AppPathwaysTantricTattwaShuddhiRoute: typeof AppPathwaysTantricTattwaShuddhiRoute
  AppPathwaysTantricYantraRoute: typeof AppPathwaysTantricYantraRoute
  AppPathwaysYogicCourseSlugRoute: typeof AppPathwaysYogicCourseSlugRoute
  AppPathwaysYogicChakrasRoute: typeof AppPathwaysYogicChakrasRouteWithChildren
  AppPathwaysYogicHubRoute: typeof AppPathwaysYogicHubRoute
  AppPathwaysYogicNadiShodhanaRoute: typeof AppPathwaysYogicNadiShodhanaRoute
  AppPathwaysYogicSuryaNamaskaraRoute: typeof AppPathwaysYogicSuryaNamaskaraRoute
  AppTeachSubmissionsSubmissionIdRoute: typeof AppTeachSubmissionsSubmissionIdRoute
  AppPathwaysBuddhistIndexRoute: typeof AppPathwaysBuddhistIndexRoute
  AppPathwaysDaoistIndexRoute: typeof AppPathwaysDaoistIndexRoute
  AppPathwaysMagickIndexRoute: typeof AppPathwaysMagickIndexRoute
  AppPathwaysTantricIndexRoute: typeof AppPathwaysTantricIndexRoute
  AppPathwaysYogicIndexRoute: typeof AppPathwaysYogicIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBhaktiRoute: AppBhaktiRoute,
  AppCoreRoute: AppCoreRouteWithChildren,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppEventsRoute: AppEventsRoute,
  AppForumRoute: AppForumRouteWithChildren,
  AppHomeworkRoute: AppHomeworkRouteWithChildren,
  AppImagesRoute: AppImagesRoute,
  AppJournalRoute: AppJournalRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMaterialRoute: AppMaterialRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSevaRoute: AppSevaRoute,
  AppTimerRoute: AppTimerRoute,
  AppVideoDemoRoute: AppVideoDemoRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppTeachEventsRoute: AppTeachEventsRoute,
  AppTeachHomeworkRoute: AppTeachHomeworkRouteWithChildren,
  AppTeachStudentsRoute: AppTeachStudentsRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppPathwaysIndexRoute: AppPathwaysIndexRoute,
  AppPathwaysBuddhistCourseSlugRoute: AppPathwaysBuddhistCourseSlugRoute,
  AppPathwaysBuddhistDeitiesRoute: AppPathwaysBuddhistDeitiesRouteWithChildren,
  AppPathwaysBuddhistHubRoute: AppPathwaysBuddhistHubRoute,
  AppPathwaysDaoistCourseSlugRoute:
    AppPathwaysDaoistCourseSlugRouteWithChildren,
  AppPathwaysDaoistBaguaTaijiRoute:
    AppPathwaysDaoistBaguaTaijiRouteWithChildren,
  AppPathwaysDaoistCosmologyRoute: AppPathwaysDaoistCosmologyRoute,
  AppPathwaysDaoistHubRoute: AppPathwaysDaoistHubRoute,
  AppPathwaysDaoistIchingRoute: AppPathwaysDaoistIchingRoute,
  AppPathwaysMagickCourseSlugRoute: AppPathwaysMagickCourseSlugRoute,
  AppPathwaysMagickHoursRoute: AppPathwaysMagickHoursRoute,
  AppPathwaysMagickHubRoute: AppPathwaysMagickHubRoute,
  AppPathwaysMagickSpagyricsRoute: AppPathwaysMagickSpagyricsRoute,
  AppPathwaysMagickTreeOfLifeRoute: AppPathwaysMagickTreeOfLifeRoute,
  AppPathwaysTantricCourseSlugRoute: AppPathwaysTantricCourseSlugRoute,
  AppPathwaysTantricCosmologyRoute: AppPathwaysTantricCosmologyRoute,
  AppPathwaysTantricHubRoute: AppPathwaysTantricHubRoute,
  AppPathwaysTantricMahavidyasRoute:
    AppPathwaysTantricMahavidyasRouteWithChildren,
  AppPathwaysTantricMantraRoute: AppPathwaysTantricMantraRoute,
  AppPathwaysTantricNyasaRoute: AppPathwaysTantricNyasaRoute,
  AppPathwaysTantricTattwaShuddhiRoute: AppPathwaysTantricTattwaShuddhiRoute,
  AppPathwaysTantricYantraRoute: AppPathwaysTantricYantraRoute,
  AppPathwaysYogicCourseSlugRoute: AppPathwaysYogicCourseSlugRoute,
  AppPathwaysYogicChakrasRoute: AppPathwaysYogicChakrasRouteWithChildren,
  AppPathwaysYogicHubRoute: AppPathwaysYogicHubRoute,
  AppPathwaysYogicNadiShodhanaRoute: AppPathwaysYogicNadiShodhanaRoute,
  AppPathwaysYogicSuryaNamaskaraRoute: AppPathwaysYogicSuryaNamaskaraRoute,
  AppTeachSubmissionsSubmissionIdRoute: AppTeachSubmissionsSubmissionIdRoute,
  AppPathwaysBuddhistIndexRoute: AppPathwaysBuddhistIndexRoute,
  AppPathwaysDaoistIndexRoute: AppPathwaysDaoistIndexRoute,
  AppPathwaysMagickIndexRoute: AppPathwaysMagickIndexRoute,
  AppPathwaysTantricIndexRoute: AppPathwaysTantricIndexRoute,
  AppPathwaysYogicIndexRoute: AppPathwaysYogicIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayDuatRaceRoute: PlayDuatRaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
